# Generated by Django 5.0.6 on 2024-06-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customer/customer_images'),
        ),
    ]
